### ISSUE TITLE
Document how to configure keepUnused for any path

### ISSUE THREAD

**Issue by fedulovivan** [daidodo/tsimportsorter#24]
For now the default behaviour is removing all unused imports except of explicitly excluded.

The idea is to add simple option, which allow to enable "keep all" behaviour easy.

Possible variants:
```
keepUnused: true // IMHO preferable
keepUnused: "all"
keepUnused: ["all"]
keepUnused: "*"
keepUnused: ["*"]
```

Current workaround is usage of:
`"keepUnused": [{ "path": "^" }]` 
(or `"keepUnused": [".*"]` as was advised by plugin author)

**Comment by daidodo** [comment]
Thanks for your feedback, @fedulovivan!

You can achieve that via:

```json
"keepUnused": [".*"]
```

I'll update the documentation and consider if `"keepUnused": ".*"` is an improvement.

Please tell me if you have more questions!

**Comment by daidodo** [comment]
After checking the code I decide NOT to implement `"keepUnused": ".*"` because:
1. It improves UX slightly, from `["pattern"]` to `"pattern"`.
2. It breaks routines for merging `"keepUnused"` config in different places, e.g. VSCode configuration, *import-sorter.json*, *packages.json*.

So I'll just update *README.md* and close the issue.
