### ISSUE TITLE
Run standalone for CI integration, initial bootstrapping, git hooks, etc.

### ISSUE THREAD

**Issue by jasonkuhrt** [daidodo/tsimportsorter#26]
VSCode plugin is fine but the ability to run standalone (e.g. cli) is important for some use-cases:

- CI integration
- pre-commit hooks
- ad-hoc usage, run over whole codebase when first getting started, etc.

**Comment by daidodo** [comment]
@jasonkuhrt Thanks for your feedback!

This is a great feature and actually it's been in the [TODO](https://github.com/daidodo/tsimportsorter/blob/master/TODO.md) list for a long time. But due to limited time it's never properly prioritised.

Currently I'm working on ESLint compatibility and I'll put this one as the next. Or it'll be even better if you or someone pick it up.

**Comment by daidodo** [comment]
Hi @jasonkuhrt 

The CLI and APIs are now in separate package [Format-Imports](https://github.com/daidodo/format-imports).
Please check it out and tell me if you have any questions.

Thanks!

**Comment by jasonkuhrt** [comment]
Thanks @daidodo! We'll check this out in the near future probably.

**Comment by jasonkuhrt** [comment]
https://twitter.com/JasonKuhrt/status/1373472671992848384
