### ISSUE TITLE
Support for maxLineLength setting in vscode-settings

### ISSUE THREAD

**Issue by Nxt3** [daidodo/tsimportsorter#39]
I've seen it recommended a few places here to use the `maxLineLength: 0` setting when running into issues with prettier.

Would it be possible to set this in vscode settings as opposed to the `importSorter` config?

**Comment by daidodo** [comment]
@Nxt3, thanks for the feedback!

Could you provide links about the issues and recommendations? I need to understand them better before making decisions.

Basically, `maxLineLength` is not in VS Code settings because it's covered by Prettier and EditorConfig. VS Code settings are generally not recommended IMHO because it's not portable in team works. But I'm open to different perspectives.

**Comment by Nxt3** [comment]
Sure: https://github.com/daidodo/tsimportsorter/issues/36#issuecomment-752201684 and https://github.com/daidodo/tsimportsorter/issues/29#issuecomment-729181831

**Comment by daidodo** [comment]
Ah, I see where you're from.

Are you having the same issue with #36? If yes, `maxLineLength` won't help you as [commented](https://github.com/daidodo/tsimportsorter/issues/36#issuecomment-752209125). The real solve for that would be either disabling formatting or compatible with Prettier.

**Comment by Nxt3** [comment]
Yes I'm running into the same problem. If there was a way to have it format so that everything is always on one line and then let prettier handle it that would probably be the fix.

**Comment by daidodo** [comment]
That's essentially running prettier after this extension, which you said couldn't achieve.

**Comment by Nxt3** [comment]
The other person was posting the issue was saying that if you had the following:
```
import { FakeImportWithVeryLooongName } from './components/fake-import-file-name-very-loooong/fake-import-file-name-very-loooong';
```

ts-import-sorter would format it like so:

```
import {
  FakeImportWithVeryLooongName
} from './components/fake-import-file-name-very-loooong/fake-import-file-name-very-loooong';
```

whereas prettier would leave it like this:

```
import { FakeImportWithVeryLooongName } from './components/fake-import-file-name-very-loooong/fake-import-file-name-very-loooong';
```

so that would imply that there is some extra processing happening in ts-import-sorter to make that happen, right?

**Comment by daidodo** [comment]
Yes, this extension pre-calculates the line length and if it exceeds the limit, it will wrap the statement.
To be honest, I don't think prettier is following the limit fully but I can implement a fall-back compatible to it.

**Comment by Nxt3** [comment]
That's correct: prettier does not format imports in that way; it's left as one-line regardless of line length.

https://prettier.io/docs/en/rationale.html#imports

**Comment by daidodo** [comment]
Thanks for the reference, that's helpful!

So what I recommend now is implementing the compatible behaviour with prettier, if it's found. Otherwise wrap the line.
What do you think?

And this shouldn't be a big change so it's more than welcome if you'd like to do it in case you're interested.

**Comment by Nxt3** [comment]
Any chance you could point me to which files to look at? If I found some time I wouldn't mind taking a stab.

**Comment by daidodo** [comment]
Sure.
Perhaps the first step is to take a look at [CONTRIBUTING.md](https://github.com/daidodo/tsimportsorter/blob/master/CONTRIBUTING.md).
The prettier config is read [here](https://github.com/daidodo/tsimportsorter/blob/master/src/config/prettier.ts) so you know if it's found.
And the start point of composing an import is [here](https://github.com/daidodo/tsimportsorter/blob/master/src/config/prettier.ts).

One note is that you might want to check whether the following are wrapped or not by prettier:

```js
import 'a-veeeeeeery-looooooooooong-veeeeeeery-looooooooooong-script';
import A = require('b-veeeeeeery-looooooooooong-veeeeeeery-looooooooooong-module');
```

As this extension WILL wrap them.

**Comment by karlhorky** [comment]
This is great, compatibility with Prettier would be awesome! Look forward to this change!

**Comment by daidodo** [comment]
@Nxt3, have you started anything on this thread? Otherwise I'm going to pick it up soon. Thanks!

**Comment by Nxt3** [comment]
@daidodo I haven't had a chance 🙃

**Comment by daidodo** [comment]
No worries, I'll pick it up then.

There are some other issues and more in the [TODO](https://github.com/daidodo/format-imports/blob/main/TODO.md) list if you still want to get your feet wet.

**Comment by daidodo** [comment]
### Prettier Study

Did a few experiments in [Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAvD3GCSAtgA4QBOMAztrjgDpQPoYAMGUAhoXJQwJYlyMDAHIOAWgBucGbLhkAnuIA2ENeo3QA5lLmzFKzUag7KYMn2IwRAbgZNMARnZc4-QRQwBBDADMyEISiHCGhYeGhIu6knsAAGgkAvn4BQSIAHgAmvtm5OflRUAIxwgBUGBzUXj7+gaLZcL6Nzb5NhcVC3tgYZHAAjgCufL0AFCIARrp68kqqRhomU3oGc-Nqi4QQmQPKcCIAlHaMx8wATADULty8RR7CAEIANBjllRgAwil1E5kcjRzZAGUXwArQA3ztO4YYAYJ4fDDJWppSgo1GoyElbzPGH3BFfZFotEYzrABgYLGwx5kj7PAAiVKgiNSwQihQcNFoGAAoukStRaPQTpg2Jxrgw4LySYl7FBmM5RW4oBLMTDqmr1RrNWqETKzpcFTdlSTYfdTWbzXD3lbrTadUrJbEyTabc8uW73e6GRgAGK+v3PBKBuIM6VCjl4Hl8-HhwXskWuQ0O4TAJnfCLpsJs2VOK6Ko2xLyptIZktZvW5xMqrzPe5Flkl1nipPQ6mWr0YenckPRsQhEQgR4gCBWPjQSjIUAcMgBADuAAUpwhxygOJIIHxMgOQOMyBwwABrOAwADKxD3fBMyBgZAGcEHcEI4zgmUyz4AMhwTAMOFo4N7yIQHAwDAF5aMgIAcAMMAQFuAAWMCEMoADqsF8PAlBnmAcDHkuaF8JIaEKOBYAoluF6UPIMBzruWiAcgILKBRg4AFaUOk9y7geR7Hq4b4XnA9EcIxd4gKx6THqBuwAIoDBA8CCcJg5nmQFFkOBMAKMQPDmJYMBbsQFiwEhG4wLByAAMwsEpAQUUhu7EOBBk8PI0hboMclwNRw7LhBlDiEqz7PluvSDMMnk0XRSAMUxIAUYQfBXjeImUJJcAyR5iW3oOMAcOMxmZKZyCnNlu58MooHvIEkUgDwACsW4DBRAAquXLtFImSLe+BQK+sDHjpVheD1x4absCkUYkiRAA)

Seems Prettier doesn't wrap an long import/export declaration except:
* There are more than one names, and
* There is a `{}`

When wrapping, there is ONE name per line.

So the extension needs the following to be compatible:

* Config:
  * `maxBindingNamesPerLine: 0`
  * `maxDefaultAndBindingNamesPerLine: 0`
  * `maxNamesPerWrappedLine: 1`
  * `maxExportNamesPerLine: 0`
* Do NOT wrap in the following cases:
  ```ts
  import 'a-veeeeeeery-looooooooooong-veeeeeeery-looooooooooong-script';
  import A from 'aaaaaaaaaaaaaaaaaa'
  import { XXX } from 'xdfdfdfdfdfdf'
  import * as AA from 'dfefefefeffe'
  import A = require('b-veeeeeeery-looooooooooong-veeeeeeery-looooooooooong-module');
  import B, * as C from 'bdaefadfadsfadgadf';

  export {} from 'aaaaaaaaaaaaaaaaa';
  export { A } from 'aaaaaaaaaaaaaaaaa';
  ```

### Recommended Solution

Add a new option `wrappingStyle` that is:

* An object with the following options:
  * maxBindingNamesPerLine
  * maxDefaultAndBindingNamesPerLine
  * maxNamesPerWrappedLine
  * maxExportNamesPerLine
* Or `'prettier'`.

When merging config, `wrappingStyle` will be replaced as whole instead of merging each option in the object.

Cons:
* Backward incompatible;

### Alternatives

#### 1. An option for not breaking lines for certain cases

Add an option, e.g. `prettierCompatible: boolean`. When it's true, don't wrap lines in the above certain cases:

Cons:
* Users need to figure out other configs to mimic Prettier behaviour, e.g. `maxBindingNamesPerLine: 0`.

#### 2. An option to do all the mimic

Add an option, e.g. `prettierWrapping: boolean`. When it's true, follow the Prettier line wrapping style and ignore `maxBindingNamesPerLine` etc. settings.

Cons:
* `maxBindingNamesPerLine` etc. settings become confusing.

### Discussions

1. Is it useful to add `prettierCompatible: boolean` to the object in the recommended solution?
No. Currently, I can't think of a use case which needs `prettierCompatible: true` without Prettier.

@Nxt3 and @karlhorky, please tell me if you have any thoughts!
Thanks!

**Comment by Nxt3** [comment]
That was a nice write-up! Thanks for putting that together.

I'm a fan of Option 2 with `prettierWrapping`. 😎

**Comment by daidodo** [comment]
Option 2 was my favourite too as a straightforward solution. But the nitpicking `maxXXX` settings made me a bit uncomfortable.

I don't have the data but generally I don't expect people use `maxXXX` settings out of Prettier compatibility issues. If that's true, I think the backward incompatibility of the recommended solution wouldn't be a problem.

**Comment by karlhorky** [comment]
Yeah, although I don't know the project too well, I would also vote for the recommended solution (breaking change, but less confusing).

There's been so many times that dealing with confusing APIs has led to hours of pain. Breaking changes mean everyone is affected, but less pain overall (and this extension is relatively "young" still, so breaking changes hurt less).

**Comment by daidodo** [comment]
@Nxt3 and @karlhorky, I've release v7.0.0 with the recommended solution.
Please check it out and tell me if you have any questions.

Thanks!

**Comment by karlhorky** [comment]
Just installed it, seems to be good so far!

One thing is that it does say that `"tsImportSorter.configuration.wrappingStyle": "prettier"` is an "Unknown Configuration Setting" - I guess that's just temporary?

![Screen Shot 2021-02-15 at 17 04 28](https://user-images.githubusercontent.com/1935696/107969540-317af100-6fb0-11eb-91e5-0ac759f34489.png)

**Comment by daidodo** [comment]
Good catch! Fix is coming.

**Comment by daidodo** [comment]
@karlhorky Please try v7.0.1.

**Comment by karlhorky** [comment]
Looks good to me, thanks!

I've added it to the [System Setup Guide](https://github.com/upleveled/system-setup) for our coding bootcamp at @upleveled and we'll use it together with the students and report any issues :)

**Comment by daidodo** [comment]
Thanks! I'll close the issue but feel free to reopen or create a new one if you have any questions.

**Comment by Nxt3** [comment]
Forgot to leave some appreciation! This turned out beautifully; makes this extension the first one to get sorting / format correct. Fantastic job and thanks again!
