### ISSUE TITLE
Backward incompatible changes in v7 and vscode extensions autoupdate

### ISSUE THREAD

**Issue by fedulovivan** [daidodo/tsimportsorter#41]
By default vscode performs [autoupdate of installed extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate). 

So moving options like *maxDefaultAndBindingNamesPerLine* from top-level scope under *wrappingStyle*  makes extension to apply default setting rather than using project-level override. This breaks formatting of existing code.

**Comment by daidodo** [comment]
Hi @fedulovivan, sorry for the inconvenience!
But the incompatible change was planned and expected ([Discussions](https://github.com/daidodo/tsimportsorter/issues/39#issuecomment-778470383)). And that's why there was a major version bump.

Back to your issue, is it possible you move the settings to `wrappingStyle`? If not, why?
I'm also interested in how `maxDefaultAndBindingNamesPerLine` etc. settings are used in your projects, so that I have better understanding of the use cases.

Please don't hesitate if you have any suggestions or ideas to improve the plugin.
Thanks!

**Comment by fedulovivan** [comment]
This is definetly not a problem to move props (already fixed). But due to autoupdate, we did not noticed that immetiately. So several committed files were re-formatted. 
Use case for *maxDefaultAndBindingNamesPerLine* is quite simple - just to keep `import { foo, bar, baz } from 'lorem'` in one line.

**Comment by daidodo** [comment]
May I know why the changes weren't found before committing?

**Comment by fedulovivan** [comment]
On a huge codebase its hard to notice the real reason of appearing such changes. It may be some old file, which was last touched before import-sorter was added to pipeline. Or re-formatting may be caused by the reason we discussing here in #41

**Comment by daidodo** [comment]
Ok. Sorry again for the inconvenience.
Is there anything I can do to help?

Maybe you'd like to know that there are [CLI and APIs](https://www.npmjs.com/package/format-imports) for use in CI/CD pipelines, on which this extension is based on.

**Comment by daidodo** [comment]
@fedulovivan, I'll close this issue if there isn't anything I can do.

Please feel free to reopen or create a new if you have further questions!
