### ISSUE TITLE
Support case like `import './style.css'`

### ISSUE THREAD

**Issue by zhusiyi111** [daidodo/tsimportsorter#5]
### Configuation:
```
    "tsImportSorter.configuration.groupRules": [
        "react",
        ".css$",
    ]
```

### Source file:
```
import React from 'react';
import './index.css';
```

### Expected:
```
import React from 'react';

import './index.css';
```

### Actually:
```
import './index.css';

import React from 'react';
```

It's seems that the groupRules doesn't support the unnamed imports.

**Comment by daidodo** [comment]
Hi @zhusiyi111, thanks for your feedback!

The rules for script imports (e.g. `import 'some/scripts'`) and non-script imports are slightly different.
In your example, both `"react"` and `".css$"` apply only to *non-script* imports.
And scripts imports are grouped all together and have higher rank than non-script imports by default. That's why you get:

```ts
import './index.css';    // Script import, grouped higher than other groups

import React from 'react';  // Non-script import grouped by "react"
```

You can define a group applying to script imports by setting `"flag": "scripts"`, e.g.:

```json
"tsImportSorter.configuration.groupRules": [
        "react",
        {"flag": "scripts", "regex": ".css$" }
    ]
```

That will get you expected results.
More details can be found in [the wiki](https://github.com/daidodo/tsimportsorter/wiki/Grouping-Rules).
Feel free to tell me if you have further questions!

Thanks!

**Comment by zhusiyi111** [comment]
Thanks! It works!
